CREATE TABLE Patient (
    IID INT PRIMARY KEY ,
    CIN VARCHAR (10) UNIQUE NOT NULL ,
    FullName VARCHAR (100) NOT NULL ,
    Birth DATE ,
    Sex ENUM ('M', 'F') NOT NULL ,
    BloodGroup ENUM ('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+','AB -'),
    Phone VARCHAR (15)
);

CREATE TABLE ContactLocation(
    CLID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    City VARCHAR(100) NOT NULL,
    Province VARCHAR(100) NOT NULL,
    Street VARCHAR(500) NOT NULL,
    Number VARCHAR(10) NOT NULL,
    Postalcode VARCHAR(10) NOT NULL,
    Phone VARCHAR(20)
);

CREATE TABLE Have(
    CLID INT NOT NULL,
    IID INT NOT NULL,
    PRIMARY KEY (CLID, IID),
    FOREIGN KEY (CLID) REFERENCES ContactLocation(CLID) ON DELETE CASCADE,
    FOREIGN KEY (IID) REFERENCES Patient(IID) ON DELETE CASCADE
);

CREATE TABLE Insurance(
    InsID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Type ENUM('CNOPS','CNSS','RAMED','Amo','private') NULL 
);


CREATE TABLE Covers(
    InsID INT NOT NULL,
    IID INT NOT NULL,
    PRIMARY KEY (InsID, IID),
    FOREIGN KEY (InsID) REFERENCES Insurance(InsID) ON DELETE CASCADE,
    FOREIGN KEY (IID) REFERENCES Patient(IID) ON DELETE CASCADE
);

CREATE TABLE Staff(
    STAFF_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Status VARCHAR(20) NOT NULL
);

CREATE TABLE Practioner(
    STAFF_ID INT NOT NULL PRIMARY KEY,
    LicenseNumber INT NOT NULL,
    Specialty VARCHAR(100) NOT NULL,
    FOREIGN KEY (STAFF_ID) REFERENCES Staff(STAFF_ID) ON DELETE CASCADE
);

CREATE TABLE Caregiving(
    STAFF_ID INT NOT NULL PRIMARY KEY,
    Grade VARCHAR(50) NOT NULL,
    Ward VARCHAR(100) NOT NULL,
    FOREIGN KEY (STAFF_ID) REFERENCES Staff(STAFF_ID) ON DELETE CASCADE
);

CREATE TABLE Technical(
    STAFF_ID INT NOT NULL PRIMARY KEY,
    Modality VARCHAR(100) NOT NULL,
    Certifications VARCHAR(100) NOT NULL,
    FOREIGN KEY (STAFF_ID) REFERENCES Staff(STAFF_ID) ON DELETE CASCADE
);

CREATE TABLE Hospital(
    HID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    City VARCHAR(100) NOT NULL,
    Region VARCHAR(100) NOT NULL
);

CREATE TABLE Department (
    DEP_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Specialty VARCHAR(100) NOT NULL,
    HID INT NOT NULL,
    FOREIGN KEY (HID) REFERENCES Hospital(HID) ON DELETE CASCADE
);

CREATE TABLE ClinicalActivity (
    CAID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Time TIME,
    Date DATE not NULL,
    IID INT NOT NULL,
    DEP_ID INT NOT NULL,
    STAFF_ID INT NOT NULL,
    FOREIGN KEY (STAFF_ID) REFERENCES Staff(STAFF_ID),
    FOREIGN KEY (IID) REFERENCES Patient(IID),
    FOREIGN KEY (DEP_ID) REFERENCES Department(DEP_ID)
);

CREATE TABLE Appointment (
    CAID INT NOT NULL PRIMARY KEY,
    Status ENUM('Scheduled', 'Completed', 'Cancelled') NULL ,
    Reason VARCHAR(255) NOT NULL,
    FOREIGN KEY (CAID) REFERENCES ClinicalActivity(CAID) ON DELETE CASCADE
);

CREATE TABLE Emergency (
    CAID INT NOT NULL PRIMARY KEY,
    TriageLevel VARCHAR(100) NOT NULL,
    Outcome VARCHAR(100) NOT NULL,
    FOREIGN KEY (CAID) REFERENCES ClinicalActivity(CAID) ON DELETE CASCADE
);

CREATE TABLE Prescription (
    PID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Time TIME,
    Date DATE,
    CAID INT NOT NULL UNIQUE,
    FOREIGN KEY (CAID) REFERENCES ClinicalActivity(CAID) ON DELETE RESTRICT
);

CREATE TABLE Expense(
    ExpID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    InsID INT,
    CAID INT UNIQUE NOT NULL ,
    Total DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (InsID) REFERENCES Insurance(InsID) ON DELETE SET NULL,
    FOREIGN KEY (CAID) REFERENCES ClinicalActivity (CAID)
);

CREATE TABLE Medication (
    Drug_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Class VARCHAR(100) NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Form VARCHAR(100) NOT NULL,
    Strength VARCHAR(100) NOT NULL,
    ActiveIngredient VARCHAR(100) NOT NULL,
    Manufacturer VARCHAR(100) NOT NULL
);
  
CREATE TABLE Stock (
    HID INT NOT NULL,
    Drug_ID INT NOT NULL,
    UnitPrice DECIMAL(10,2) NOT NULL,
    StockTimestamp DATETIME NOT NULL,
    Qty INT NOT NULL,
    ReorderLevel INT NOT NULL,
    PRIMARY KEY (HID, Drug_ID),
    FOREIGN KEY (HID) REFERENCES Hospital(HID) ON DELETE CASCADE,
    FOREIGN KEY (Drug_ID) REFERENCES Medication(Drug_ID) ON DELETE CASCADE
);
 
 CREATE TABLE include (
    PID INT NOT NULL,
    Drug_ID INT NOT NULL,
    dosage VARCHAR(50) NOT NULL,
    duration INT NOT NULL,
    PRIMARY KEY (PID, Drug_ID),
    FOREIGN KEY (PID) REFERENCES Prescription(PID) ON DELETE CASCADE,
    FOREIGN KEY (Drug_ID) REFERENCES Medication(Drug_ID) ON DELETE CASCADE
);
   
 CREATE TABLE work_in (
    STAFF_ID INT NOT NULL,
    DEP_ID INT NOT NULL,
    PRIMARY KEY(STAFF_ID,DEP_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES Staff(STAFF_ID) ON DELETE CASCADE,
    FOREIGN KEY (DEP_ID) REFERENCES Department(DEP_ID) ON DELETE CASCADE
);


ALTER TABLE Patient ADD email varchar(255);