CREATE TABLE Patient(
    IID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CIN VARCHAR(100) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Sex VARCHAR(1) NOT NULL CHECK(Sex IN ('M','F')),
    Birth DATE NOT NULL,
    Blood_group VARCHAR(10) NOT NULL,
    Phone VARCHAR(20)
);

CREATE TABLE Contact_Location(
    CLID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    province VARCHAR(100) NOT NULL,
    Street VARCHAR(500) NOT NULL,
    Number VARCHAR(10) NOT NULL,
    postal_code VARCHAR(10) NOT NULL,
    Phone VARCHAR(20)
);