CREATE TABLE Patient(
    IID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CIN VARCHAR(100) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Sex VARCHAR(1) NOT NULL CHECK(Sex IN ('M','F')),
    Birth DATE NOT NULL,
    Blood_group VARCHAR(10) NOT NULL,
    Phone VARCHAR(20)
);

CREATE TABLE Contact_Location(
    CLID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    City VARCHAR(100) NOT NULL,
    Province VARCHAR(100) NOT NULL,
    Street VARCHAR(500) NOT NULL,
    Number VARCHAR(10) NOT NULL,
    Postal_code VARCHAR(10) NOT NULL,
    Phone VARCHAR(20)
);

CREATE TABLE Have(
    CLID INT NOT NULL,
    IID INT NOT NULL,
    PRIMARY KEY (CLID, IID),
    FOREIGN KEY (CLID) REFERENCES Contact_Location(CLID) ON DELETE CASCADE,
    FOREIGN KEY (IID) REFERENCES Patient(IID) ON DELETE CASCADE
);

CREATE TABLE Insurance(
    InsID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Ins_type VARCHAR(10) CHECK (Ins_type in ('CNOPS', 'CNSS', 'RAMED', 'private') OR Ins_type IS NULL)
);

CREATE TABLE Expense(
    ExID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    InsID INT,
    Total DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (InsID) REFERENCES Insurance(InsID) ON DELETE SET NULL
);

CREATE TABLE Covers(
    InsID INT NOT NULL,
    IID INT NOT NULL,
    PRIMARY KEY (InsID, IID),
    FOREIGN KEY (InsID) REFERENCES Insurance(InsID) ON DELETE CASCADE,
    FOREIGN KEY (IID) REFERENCES Patient(IID) ON DELETE CASCADE
);

CREATE TABLE Staff(
    Staff_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Status VARCHAR(20) NOT NULL
);

CREATE TABLE Practioner(
    Staff_ID INT NOT NULL PRIMARY KEY,
    License_Number INT NOT NULL,
    Specialty VARCHAR(100) NOT NULL,
    FOREIGN KEY (Staff_ID) REFERENCES Staff(Staff_ID) ON DELETE CASCADE
);

CREATE TABLE Caregiving(
    Staff_ID INT NOT NULL PRIMARY KEY,
    Grade VARCHAR(50) NOT NULL,
    Ward VARCHAR(100) NOT NULL,
    FOREIGN KEY (Staff_ID) REFERENCES Staff(Staff_ID) ON DELETE CASCADE
);

CREATE TABLE Technical(
    Staff_ID INT NOT NULL PRIMARY KEY,
    Modality VARCHAR(100) NOT NULL,
    Certifications VARCHAR(100) NOT NULL,
    FOREIGN KEY (Staff_ID) REFERENCES Staff(Staff_ID) ON DELETE CASCADE
);

CREATE TABLE Hospital(
   HID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   Name VARCHAR(100) NOT NULL,
   City VARCHAR(100) NOT NULL,
   Region VARCHAR(100) NOT NULL
);


CREATE TABLE Department (
    DEP_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Specialty VARCHAR(100) NOT NULL,
    HID INT NOT NULL,
    FOREIGN KEY (HID) REFERENCES Hospital(HID) ON DELETE CASCADE
);



CREATE TABLE Clinical_Activity (
    CAID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    occurred_at DATETIME NOT NULL,
    IID INT NOT NULL,
    ExID INT UNIQUE NOT NULL,
    DEP_ID INT NOT NULL,
    STAFF_ID INT NOT NULL,
    FOREIGN KEY (STAFF_ID) REFERENCES Staff(STAFF_ID) ON DELETE RESTRICT,
    FOREIGN KEY (IID) REFERENCES Patient(IID) ON DELETE RESTRICT,
    FOREIGN KEY (ExID) REFERENCES Expense(ExID),
    FOREIGN KEY (DEP_ID) REFERENCES Department(DEP_ID)
);

CREATE TABLE Appointment (
    CAID INT NOT NULL PRIMARY KEY,
    Status VARCHAR(10) CHECK (Status IN ('Scheduled', 'Completed', 'Cancelled') OR Status IS NULL),
    Reason VARCHAR(255) NOT NULL,
    FOREIGN KEY (CAID) REFERENCES Clinical_Activity(CAID) ON DELETE CASCADE
);

CREATE TABLE Emergency (
    CAID INT NOT NULL PRIMARY KEY,
    Triage_Level VARCHAR(100) NOT NULL,
    Outcome VARCHAR(100) NOT NULL,
    FOREIGN KEY (CAID) REFERENCES Clinical_Activity(CAID) ON DELETE CASCADE
);


CREATE TABLE Prescription (
    PID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Date_Issued DATE NOT NULL,
    CAID INT NOT NULL UNIQUE,
    FOREIGN KEY (CAID) REFERENCES Clinical_Activity(CAID) ON DELETE RESTRICT
);

CREATE TABLE Medication (
  DrugID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Class VARCHAR(100) NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Form VARCHAR(100) NOT NULL,
  Strength VARCHAR(100) NOT NULL,
  Active_Ingredient VARCHAR(100) NOT NULL,
  Manufacturer VARCHAR(100) NOT NULL
 );
  
  
CREATE TABLE Stock (
  HID INT NOT NULL,
  DrugID INT NOT NULL,
  Unit_Price DECIMAL(10,2) NOT NULL,
  Stock_Timestamp DATETIME NOT NULL,
  Quantity INT NOT NULL,
  Reorder_Level INT NOT NULL,
  PRIMARY KEY (HID, DrugID),
  FOREIGN KEY (HID) REFERENCES Hospital(HID) ON DELETE CASCADE,
  FOREIGN KEY (DrugID) REFERENCES Medication(DrugID) ON DELETE CASCADE
 );
 
 CREATE TABLE include (
   PID INT NOT NULL,
   DrugID INT NOT NULL,
   PRIMARY KEY (PID, DrugID),
   FOREIGN KEY (PID) REFERENCES Prescription(PID) ON DELETE CASCADE,
   FOREIGN KEY (DrugID) REFERENCES Medication(DrugID) ON DELETE CASCADE
   );
   
 CREATE TABLE work_in (
   STAFF_ID INT NOT NULL,
   DEP_ID INT NOT NULL,
   PRIMARY KEY(STAFF_ID,DEP_ID),
   FOREIGN KEY (STAFF_ID) REFERENCES Staff(STAFF_ID) ON DELETE CASCADE,
   FOREIGN KEY (DEP_ID) REFERENCES Department(DEP_ID) ON DELETE CASCADE
  );
