CREATE TABLE Patient(
   IID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   CIN VARCHAR(100) NOT NULL,
   Name VARCHAR(100) NOT NULL,
   Sex VARCHAR(500) NOT NULL,
   Birth DATE NOT NULL,
   Blood_group VARCHAR(10) NOT NULL,
   Phone VARCHAR(20),
   PRIMARY KEY (IID)
);

CREATE TABLE Contact_Location (
    CLID INT NOT NULL AUTO_INCREMENT,
    city VARCHAR(100) NOT NULL,
    province VARCHAR(100) NOT NULL,
    Street VARCHAR(500) NOT NULL,
    number VARCHAR(10) NOT NULL,
    postal_code VARCHAR(10) NOT NULL,
    phone VARCHAR(20),
    PRIMARY KEY (CLID)
);

CREATE TABLE Have (
    IID INT NOT NULL,
    CLID INT NOT NULL,
    PRIMARY KEY (IID, CLID),
    FOREIGN KEY (IID) REFERENCES Patient(IID),
    FOREIGN KEY (CLID) REFERENCES Contact_Location(CLID)
);

CREATE TABLE Insurance (
    InsID INT NOT NULL AUTO_INCREMENT,
    ins_type VARCHAR(10) CHECK (type in ('CNOPS', 'CNSS', 'RAMED', 'private') OR type IS NULL),
);

CREATE TABLE Expenses(
   ExID INT NOT NULL,
   total FLOAT NOT NULL,
);

CREATE TABLE Attached(
    ExID INT NOT NULL,
    InsID INT NOT NULL,
    PRIMARY ExID,
    FOREIGN KEY (ExID) REFERENCES Expenses(ExID);
    FOREIGN KEY (InsID) REFERENCES Insurance(ExID);

);

CREATE TABLE Staff(
   STAFF_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   Name VARCHAR(100) NOT NULL,
   Status VARCHAR(20) NOT NULL,
   DEP_ID INT NOT NULL 
   FOREIGN KEY(DEP_ID) REFERENCES Department(DEP_ID)
);
CREATE TABLE Practioner(
    Staff_ID INT PRIMARY KEY,
    License_Number INT NOT NULL,
    Specialty VARCHAR(100) NOT NULL,
    FOREIGN KEY(Staff_ID) REFERENCES Staff(Staff_ID)
);
CREATE TABLE Caregiving(
    Staff_ID INT PRIMARY KEY,
    Grade VARCHAR(50) NOT NULL,
    Ward VARCHAR(100) NOT NULL,
    FOREIGN KEY(Staff_ID) REFERENCES Staff(Staff_ID)
);
CREATE TABLE Technical(
    Staff_ID INT PRIMARY KEY,
    Modality VARCHAR(100) NOT NULL,
    Certifications VARCHAR(100) NOT NULL,
    FOREIGN KEY(Staff_ID) REFERENCES Staff(Staff_ID)
);
CREATE TABLE Department(
   DEP_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   Name VARCHAR(100) NOT NULL,
   Specialty VARCHAR(100) NOT NULL,
   HID INT UNIQUE,
   FOREIGN KEY(HID) REFERENCES Hospital(HID)
);
